{% set version = "0.0.16" %}


package:
  name: hologram
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/h/hologram/hologram-{{ version }}.tar.gz
    sha256: 1c2c921b4e575361623ea0e0d0aa5aee377b1a333cc6c6a879e213ed34583e55
  - folder: src
    url: https://github.com/dbt-labs/hologram/archive/refs/tags/v{{ version }}.tar.gz
    sha256: b9d241a93624c7926035e181424b7be44fc398bf68285823c27532e91ff992da
    patches:
      - 0001-use-default-factory.patch

build:
  noarch: python
  number: 1
  script:
    - cd dist && "{{ PYTHON }}" -c "__import__('shutil').rmtree('tests')"
    - cd "{{ SRC_DIR }}/dist" && "{{ PYTHON }}" -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - jsonschema >=3.0
    - python >={{ python_min }}
    - python-dateutil >=2.8,<2.9

test:
  source_files:
    - src/tests
  requires:
    - pip
    - pytest-cov
    - python {{ python_min }}
  imports:
    - hologram
  commands:
    - pip check
    - cd src && pytest --pyargs tests -vv --cov=hologram --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=90

about:
  home: https://github.com/fishtown-analytics/hologram
  summary: JSON schema generation from dataclasses
  license: MIT
  license_file: dist/LICENSE

extra:
  recipe-maintainers:
    - thewchan
